### ISSUE TITLE
write permission check using github API

### ISSUE THREAD

**Issue by gautamkrishnar** [gautamkrishnar/keepalive-workflow#17]
- [x] If branch protection is enabled, exit with an error
- [ ] Using GitHub API check if the branch is protected.  If it's protected, exit with error

ref: #13

**Comment by gautamkrishnar** [comment]
it looks like github api do not support it right now:
```
curl -sS -f -H "Authorization: token <token>" https://api.github.com/repos/example-user/example-repo  | jq .permissions
{
  "admin": false,
  "maintain": false,
  "push": false,
  "triage": false,
  "pull": false
}
```
This is the response we always get. 

there are other users who also have same problem: https://github.com/orgs/community/discussions/25259

**Comment by lgmorand** [comment]
maybe you could just check the current branch status because token scope won't help in any case I think

https://api.github.com/repos/OWNER/REPO/branches/BRANCH/protection

It would report if the current branch is protected or not. if yes, add a warning/exit

**Comment by gautamkrishnar** [comment]
@lgmorand, it looks like there is an even simpler way to detect branch protection just by using process.env.GITHUB_REF_PROTECTED === 'true'

But this won't still fix the token permission issue though. We still need to use the token permission API to determine if the token provided has write access to the repo.  But adding branch protection check is the first step.

**Comment by lgmorand** [comment]
indeed. Branch protection is something you can't do much. but helping to understand that token doesn't have enough rights could be useful

**Comment by gautamkrishnar** [comment]
Will re-open this later, once Github fixes their API.
