### ISSUE TITLE
Unexpected input(s) 'use_api' during action run

### ISSUE THREAD

**Issue by Infinage** [gautamkrishnar/keepalive-workflow#23]
I followed the documentation and here is the link to my [YAML](https://github.com/Infinage/tneb-scraper/blob/main/.github/workflows/schedule-scraper.yml) file. For some reason, the step is skipped and it seems like it doesn't do anything. Assistance would be greatly appreciated. I would prefer not to create any new commits. 

![image](https://github.com/gautamkrishnar/keepalive-workflow/assets/37257700/10bc0102-0d8e-4d68-8c80-40cd8576a182)

My PAT has the following access:
`Github Action - Keep Alive — admin:repo_hook, repo, workflow`

Any assistance / directions would be greatly appreciated. Thanks in advance!

**Comment by gautamkrishnar** [comment]
@Infinage it is not yet released. I was just testing it myself.

**Comment by gautamkrishnar** [comment]
@Infinage I just released https://github.com/gautamkrishnar/keepalive-workflow/releases/tag/1.2.4 it will fix that message. Please note that it needs `actions:write` permission for it to work properly. Refer: https://github.com/gautamkrishnar/keepalive-workflow?tab=readme-ov-file#github-api-keepalive-workflow-for-github-actions-users

**Comment by gautamkrishnar** [comment]
Yes it is expected. It is not needed to do anything until it reaches 50 days time elapsed from the last commit
