### ISSUE TITLE
Please update Release 2.0 to say explicitly what needs to change

### ISSUE THREAD

**Issue by rfay** [gautamkrishnar/keepalive-workflow#27]
in https://github.com/gautamkrishnar/keepalive-workflow/releases/tag/2.0.0 you say

> People who are using v1 and master tags of this workflow will continue using the dummy commit method since the newly added API-based method requires explicit permission for the API Keys for it to function.

but you don't mention what permission has to be changed.

It looks to me like you're saying that 
```
permissions:
  contents: write
```

must be changed to:

```yaml
permissions:
  actions: write
```

Could you please just show the simple change of an action in the release notes (and probably in the README?)

Thanks for all the work on this!

**Comment by gautamkrishnar** [comment]
@rfay thats a good suggestion. Will add more info on the readme. Most people will rather continue using version 1 that's the main reason why I never added that.

**Comment by rfay** [comment]
I don't agree! It's a great new feature, and those commits were a real pain, completely obscuring the history of the repo.

The only thing I don't know is... how do I know it's working? I put a TODO to remember to check one of the repos I changed in 2 months :)

**Comment by gautamkrishnar** [comment]
Yea, I also agree that commits are a real pain. 

As far as I know https://github.com/gautamkrishnar/keepalive-workflow/issues/1#issuecomment-1945644242 suggested that it's working fine. I also tested using some pre-dated commits and it worked just fine.

**Comment by rfay** [comment]
I don't doubt it... just wish there was some output or something that gave me confidence. We'll change https://github.com/ddev/github-action-add-on-test to use v2 and it will affect many, many repositories, and if their tests stop running we may not notice for ages.

* https://github.com/ddev/github-action-add-on-test/issues/27

Thanks!

**Comment by gautamkrishnar** [comment]
Updated this in the changelog as well, Thanks again for the suggestion @rfay

**Comment by gautamkrishnar** [comment]
> I don't doubt it... just wish there was some output or something that gave me confidence.

@rfay it shows output on the test logs, after 50 days of inactivity it will start calling the API. 

If you wanna see it calling the API immediately, simply set the `time_elapsed` option to 0. Other than that waiting for the next 50 days is the only option for active repositories.
