### ISSUE TITLE
Action does not complete and causes the parent workflow to fail. (triggered by pull request from fork)

### ISSUE THREAD

**Issue by julienloizelet** [gautamkrishnar/keepalive-workflow#42]
For some reason, one of our actions fails and it seems to be due to the keepalive-workflow step: 

https://github.com/justafish/ddev-drupal-core-dev/actions/runs/9213831558/job/25348604861

As you can see, the logs states that the action starts:

`Executing keepalive for parent workflow (justafish/ddev-drupal-core-dev/.github/workflows/tests.yml)` 

But there is nothing after this: I expect to have `Nothing to do ... `  or `Kept the repo active using GitHub API`

I assume that the step does not end with an exit code 0, which causes the workflow to fail.

More information:

- we are using here 0 as time_elapsed
- this is a workflow triggered by a pull request (coming from a fork)

Do you have any idea of what could be the problem ?

Thanks!

**Comment by julienloizelet** [comment]
After some more debugging, I was able to reproduce the behavior.

It appears for me to be related to a workflow triggered by a pull request coming from a fork...

- Tested a simple push: https://github.com/julienloizelet/ddev-tools/actions/runs/9218616534 : OK
- Tested a pull request from the same repo: https://github.com/julienloizelet/ddev-tools/actions/runs/9216511322 : OK

- Tested a pull request from a fork: https://github.com/julienloizelet/ddev-tools/actions/runs/9218544567 : FAILED with a silent error


I think it's perfectly legitimate for a PR not to be able to trigger the "keep alive" API call: but perhaps you could do something to avoid this error?

Thanks

**Comment by gautamkrishnar** [comment]
@julienloizelet thanks for the suggestion, yep this can be added. A check for pr and a message would be fine in this case. Will add that.
