### ISSUE TITLE
If API execution fails, an error does not occur

### ISSUE THREAD

**Issue by iloveitaly** [gautamkrishnar/keepalive-workflow#49]
https://github.com/iloveitaly/pihole-scheduled-blocking/actions/runs/12100711495

Noticed that the workflow was not failing even though a commit was not generated. I'm guessing this is because write permissions were not granted but the workflow did not notice any failures to write. Would be great if the workflow failed if the right API permissions are not granted.

**Comment by gautamkrishnar** [comment]
@iloveitaly is there any reason why you think that workflow failed to do the keepalive?. From the output of the workflow, it looks like it succeeded.  https://github.com/iloveitaly/pihole-scheduled-blocking/actions/runs/12100711495/job/33739670380#step:8:12

The code to check for API faIlure is already there:
https://github.com/gautamkrishnar/keepalive-workflow/blob/version2/library.js#L112-L117

**Comment by iloveitaly** [comment]
> If your concern is related to the absence of a commit, that’s expected. Starting with version 2, the workflow no longer relies on a commit-based approach.

Interesting! This is definitely the main goal for me. I got a notification that my workflow was disabled, which is why I ended up looking into this. 

Do you have any idea why the keep alive didn't work for me?

**Comment by gautamkrishnar** [comment]
@iloveitaly no idea why it didnt work for you. For me, it has been working just fine. Justr let me know if your workflows are getting deactivated again in the future.
